fieldLayouts:
  af0c5da0-22c8-4294-9774-adeda105d90d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f386c501-34ff-4208-8177-aec3088357ca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6aad5e8f-7b65-4801-9462-f2016190d987 # magazine
            instructions: 'here you upload the pdf of the magazine (no bleed lines).'
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b56774dc-cdf6-4cd2-bf3c-71960fda80c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6609f9f3-812e-40d4-84c4-e9e5e467b33d # issue date
            instructions: 'what month and year is this issue published in?'
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec083783-ef9a-4a75-8758-9bc4f77d6645
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 43d610cc-1f89-426c-b57f-9f1def3f22f5 # issue number
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 082fcf90-9045-4d55-9911-3f575657c20b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2d48633e-8695-49d5-a2d6-b11041079468
            instructions: 'summarize the main topics of the magazine, this could be similar to what is on front of the magazine.'
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80e386dc-2d00-4cda-ab68-c1845042e84b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec282539-3cf4-46f1-b8e2-62016da734c5 # keywords
            instructions: 'write down anything that is talked about in this issue. these words will be used to make sure users can look up issues based on their content through the search bar'
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2aa3182-13b5-4472-af40-8e6a1ae50332
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c56de0da-5b44-478c-923b-0fbe204518f9 # articles to reply to 
            instructions: 'if there are any articles that asked readers to reply to it, mention each of those article here.'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e6470d1-26a5-45e4-8dc3-f6f6de69f328
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4f0cc8fa-2ae2-4a45-8f9a-0d077cace9ff
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: ccd8aaae-5c1c-4541-930b-d49e46fbfab4 # Magazines
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
