fieldLayouts:
  beba441b-0489-4324-b2d5-c45bea22f9f8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fc6b4836-8b30-436f-9330-bb9089f9ccf8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 016e84f9-ad52-467d-ad64-15d59d126ea4 # image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99890d58-6dff-40d6-8bdc-cd4e13d52bd2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5001e355-1c2e-4928-af3b-42af9458c17e # text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44f17d7b-70b1-4e65-b878-02048b042585
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3987927b-d36a-44c4-930a-b96c1a37bb7f # extra info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4013457f-ee71-4d33-a8e6-4d6ab8825b9b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa2997a3-0cb2-4f4b-beaf-5cf0e53dedbc # magazine section
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f570d7a8-4622-462e-9a5b-93c39f6b5409
            userCondition: null
            warning: null
            width: 100
        name: 'Submission content'
        uid: d48ab4b1-9500-4ae1-8101-8a3b6e4c744a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c6dd7f8a-0019-41b8-af12-1f61cb29d8b0 # approval status
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d811232-3eea-4aca-a024-1f2472c2eceb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 42af299d-19ac-41c5-b3a9-39d32ccaca4a # featured?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4141be52-b1b2-46e8-a190-62fe28fea37e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 43d610cc-1f89-426c-b57f-9f1def3f22f5 # issue number
            instructions: 'specify what issue this submission will be included in when you approve a submission.'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6441db4-4299-4ce6-a2cf-2fc5bce41600
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9abc582e-b96c-4a01-9269-f393c293d53d # page number
            instructions: 'write down here what page of the magazine this submission will end up on. this is especially important if this is an article that will be featured on the home page.'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1c42343-fef0-4445-8da8-aeb58d95b8e0
            userCondition: null
            warning: null
            width: 100
        name: 'Approval and info'
        uid: 37b544ed-7d25-4a83-bfa9-39dbbc210d3e
        userCondition: null
handle: default
hasTitleField: true
name: default
section: b192fdca-10c6-4d05-9523-9a3c207b4894 # Submissions
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
