fieldLayouts:
  68c47fdf-367d-4233-819b-8b7e5c51be90:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a9c2d650-a626-443f-9bfd-9a244b17d114
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5001e355-1c2e-4928-af3b-42af9458c17e # text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02cc8d62-aedd-4670-b6a6-e64d2db55b59
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa2997a3-0cb2-4f4b-beaf-5cf0e53dedbc # magazine section
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd002d30-0dcc-4e7c-96e7-7f8109c03a6b
            userCondition: null
            warning: null
            width: 100
        name: 'Submission content'
        uid: f06fd7ec-4f2a-4d62-b285-f7893fda25b6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c6dd7f8a-0019-41b8-af12-1f61cb29d8b0 # approval status
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98a0fee7-7649-4961-af84-96299f0e7adf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 43d610cc-1f89-426c-b57f-9f1def3f22f5 # issue number
            instructions: 'specify what issue this submission will be included in when you approve a submission.'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b2ba4b5-fa47-49f8-930b-4f1474c839ea
            userCondition: null
            warning: null
            width: 100
        name: 'Approval and info'
        uid: 709aba2a-7951-4fa8-9ef9-e4037f1d830b
        userCondition: null
handle: textSubmission
hasTitleField: true
name: 'text submission'
section: b192fdca-10c6-4d05-9523-9a3c207b4894 # Submissions
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
