field: 2d48633e-8695-49d5-a2d6-b11041079468 # featured topics
fieldLayouts:
  0f6661f1-3ac9-48fc-b55b-c32c86216ae2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 238f07e6-f4bd-48c1-8de9-8eb03b03202f # Topic
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3d5ffec-7c7d-4bef-a006-0ec545ee0605
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 11b41111-d559-44cc-a321-66115daf4351
        userCondition: null
fields:
  238f07e6-f4bd-48c1-8de9-8eb03b03202f: # Topic
    columnSuffix: nwcnrygr
    contentColumnType: text
    fieldGroup: null
    handle: topic
    instructions: null
    name: Topic
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: topic
name: topic
sortOrder: 1
