dateModified: 1687006424
email:
  fromEmail: maite.lejeune@student.howest.be
  fromName: 'Kortrijk 2030'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: images
    settings:
      path: files/images
    type: craft\fs\Local
    url: /files/images
  magazines:
    hasUrls: true
    name: magazines
    settings:
      path: files/magazines
    type: craft\fs\Local
    url: /files/magazines
meta:
  __names__:
    0a679b1b-7494-4145-9b3e-b61d860ad689: default # default
    1c207f6e-8c50-4860-a960-ccdd0a6a4d5f: 'Kortrijk 2030' # Kortrijk 2030
    2a0b235e-6f75-4298-b15e-f28e3bec4452: 'option name' # option name
    2d477dbf-80bf-49d3-b495-f0073932f385: 'Font-end users' # Font-end users
    3be20871-ea45-45e2-a115-78a17368d0dd: submissions # submissions
    4a117e71-b04d-44ea-acee-4bd7ef1868fc: 'Public Schema' # Public Schema
    6aad5e8f-7b65-4801-9462-f2016190d987: magazine # magazine
    7c04bd97-c2ed-4afb-a845-3fadfd2bc967: Default # Default
    7c37efd5-f741-4f04-b923-3348e2d86391: 'Private Schema' # Private Schema
    8c9b42bd-a9c2-4358-ace3-cc4ad0e2cc40: 'vote amount' # vote amount
    9abc582e-b96c-4a01-9269-f393c293d53d: 'page number' # page number
    016e84f9-ad52-467d-ad64-15d59d126ea4: image # image
    42af299d-19ac-41c5-b3a9-39d32ccaca4a: 'featured?' # featured?
    43d610cc-1f89-426c-b57f-9f1def3f22f5: 'issue number' # issue number
    54fea167-e282-4701-8f9c-c5a9d65f85b5: option2 # option2
    93d3d13d-83fd-4ffc-9ec8-99e36ab263aa: 'section group' # section group
    99c508e5-a234-4f38-80f1-9bade78787f0: time # time
    238f07e6-f4bd-48c1-8de9-8eb03b03202f: Topic # Topic
    825d900f-d973-45c3-bb99-5b5fb09d7ccd: 'Kortrijk 2030' # Kortrijk 2030
    874b6adc-a507-4177-af8a-854f21ce0f38: 'option name' # option name
    5001e355-1c2e-4928-af3b-42af9458c17e: text # text
    5532ab28-2cc4-40fc-aa89-be46645ae30b: title # title
    6609f9f3-812e-40d4-84c4-e9e5e467b33d: 'issue date' # issue date
    059366aa-5dad-411e-a9d9-08c0d05dec3c: sections # sections
    69053c9d-206a-42d1-83b7-3282638db454: Polls # Polls
    324575b1-4aa1-470b-a0b3-45adf161a21b: 'poll options' # poll options
    3987927b-d36a-44c4-930a-b96c1a37bb7f: 'extra info' # extra info
    9792054f-bb1c-4d58-bb44-0b3a55bf61be: 'option 1' # option 1
    a6720840-f082-4e30-bafe-b8176bf62ccc: Common # Common
    b5d3c9ba-50b0-44b2-9a96-91c21d93f970: article # article
    b192fdca-10c6-4d05-9523-9a3c207b4894: Submissions # Submissions
    c6dd7f8a-0019-41b8-af12-1f61cb29d8b0: 'approval status' # approval status
    c56de0da-5b44-478c-923b-0fbe204518f9: 'articles to reply to ' # articles to reply to 
    ccd8aaae-5c1c-4541-930b-d49e46fbfab4: Magazines # Magazines
    e5273228-0fc4-445e-929d-9a7b9f4e6ba6: Default # Default
    ec282539-3cf4-46f1-b8e2-62016da734c5: keywords # keywords
    f1b76377-5de4-4c7e-88bc-1bd49d48eaf9: magazines # magazines
    fa2997a3-0cb2-4f4b-beaf-5cf0e53dedbc: 'magazine section' # magazine section
    fc00d814-fa02-444e-9510-35f369b22977: 'vote amount' # vote amount
plugins:
  graphql-authentication:
    edition: standard
    enabled: true
    licenseKey: MMXOMAHLXTYMIMJCKA08Q86E
    schemaVersion: 1.3.0
    settings:
      accountCooldown: 'Too many log in attempts; please try again shortly'
      accountDeleted: 'Successfully deleted account'
      accountLocked: 'Sorry, your account is currently locked'
      activationEmailSent: 'You will receive an email if it matches an account in our system'
      allowMagicAuthentication: null
      allowRegistration: '1'
      allowedFacebookDomains: null
      allowedGoogleDomains: null
      allowedMicrosoftDomains: null
      allowedTwitterDomains: null
      appleClientId: null
      appleClientSecret: null
      appleRedirectUrl: null
      appleServiceId: null
      appleServiceSecret: null
      assetMutations:
        __assoc__:
          -
            - submissions
            - ''
          -
            - magazines
            - ''
      assetNotFound: 'We couldn''t find any matching assets'
      assetQueries:
        __assoc__:
          -
            - submissions
            - ''
          -
            - magazines
            - ''
      emailNotInScope: 'No email in scope'
      entryMutations:
        __assoc__:
          -
            - polls
            - ''
          -
            - submissions
            - ''
      entryNotFound: 'We couldn''t find any matching entries'
      entryQueries:
        __assoc__:
          -
            - magazines
            - ''
          -
            - polls
            - ''
          -
            - submissions
            - ''
      facebookAppId: null
      facebookAppSecret: null
      facebookEmailMismatch: 'Email address doesn''t match allowed Facebook domains'
      facebookRedirectUrl: null
      fieldRestrictions:
        __assoc__:
          -
            - schema-1
            -
              __assoc__:
                -
                  - approvalStatus
                  - queryMutate
                -
                  - articlesToReplyTo
                  - queryMutate
                -
                  - extraInfo
                  - queryMutate
                -
                  - featured
                  - queryMutate
                -
                  - image
                  - queryMutate
                -
                  - issueDate
                  - queryMutate
                -
                  - issueNumber
                  - queryMutate
                -
                  - keywords
                  - queryMutate
                -
                  - magazine
                  - queryMutate
                -
                  - magazineSection
                  - queryMutate
                -
                  - pageNumber
                  - queryMutate
                -
                  - pollOptions
                  - queryMutate
                -
                  - sectionGroup
                  - queryMutate
                -
                  - text
                  - queryMutate
                -
                  - time
                  - queryMutate
          -
            - 'schema-Private Schema'
            -
              __assoc__:
                -
                  - approvalStatus
                  - queryMutate
                -
                  - articlesToReplyTo
                  - queryMutate
                -
                  - extraInfo
                  - queryMutate
                -
                  - featured
                  - queryMutate
                -
                  - image
                  - queryMutate
                -
                  - issueDate
                  - queryMutate
                -
                  - issueNumber
                  - queryMutate
                -
                  - keywords
                  - queryMutate
                -
                  - magazine
                  - queryMutate
                -
                  - magazineSection
                  - queryMutate
                -
                  - pageNumber
                  - queryMutate
                -
                  - pollOptions
                  - queryMutate
                -
                  - sectionGroup
                  - queryMutate
                -
                  - text
                  - queryMutate
                -
                  - time
                  - queryMutate
          -
            - 'schema-Public Schema'
            -
              __assoc__:
                -
                  - approvalStatus
                  - queryMutate
                -
                  - articlesToReplyTo
                  - queryMutate
                -
                  - extraInfo
                  - queryMutate
                -
                  - featured
                  - queryMutate
                -
                  - image
                  - queryMutate
                -
                  - issueDate
                  - queryMutate
                -
                  - issueNumber
                  - queryMutate
                -
                  - keywords
                  - queryMutate
                -
                  - magazine
                  - queryMutate
                -
                  - magazineSection
                  - queryMutate
                -
                  - pageNumber
                  - queryMutate
                -
                  - pollOptions
                  - queryMutate
                -
                  - sectionGroup
                  - queryMutate
                -
                  - text
                  - queryMutate
                -
                  - time
                  - queryMutate
      forbiddenField: 'User doesn''t have permission to access requested field(s)'
      forbiddenMutation: 'User doesn''t have permission to perform this mutation'
      googleClientId: null
      googleEmailMismatch: 'Email address doesn''t match allowed Google domains'
      googleTokenIdInvalid: 'Invalid Google Token ID'
      granularSchemas: null
      invalidEmailAddress: 'Invalid email address'
      invalidHeader: 'Invalid Authorization Header'
      invalidJwtSecretKey: 'Invalid JWT Secret Key'
      invalidLogin: 'We couldn''t log you in with the provided details'
      invalidMagicCode: 'Invalid magic code'
      invalidOauthToken: 'Invalid OAuth Token'
      invalidPasswordMatch: 'Passwords do not match'
      invalidPasswordUpdate: 'We couldn''t update the password with the provided details'
      invalidRefreshToken: 'Invalid Refresh Token'
      invalidRequest: 'Cannot validate request'
      invalidSchema: 'No schema has been set for this user group'
      invalidUserUpdate: 'We couldn''t update the user with the provided details'
      jwtExpiration: '30 minutes'
      jwtRefreshExpiration: '3 months'
      jwtSecretKey: KghTP-MPc3Uj0k17SvEnC7O770d55Mzj
      magicLinkSent: 'You will receive an email if it matches an account in our system'
      microsoftAppId: null
      microsoftAppSecret: null
      microsoftEmailMismatch: 'Email address doesn''t match allowed Microsoft domains'
      microsoftRedirectUrl: null
      passwordResetRequired: 'Password reset required; please check your email'
      passwordResetSent: 'You will receive an email if it matches an account in our system'
      passwordSaved: 'Successfully saved password'
      passwordUpdated: 'Successfully updated password'
      permissionType: single
      sameSitePolicy: strict
      schemaId: null
      schemaName: 'Private Schema'
      siteId: null
      skipActivatedCheck: ''
      skipSocialActivation: null
      tokenNotFound: 'We couldn''t find any matching tokens'
      twitterApiKey: null
      twitterApiKeySecret: null
      twitterEmailMismatch: 'Email address doesn''t match allowed Twitter domains'
      twitterRedirectUrl: null
      userActivated: 'Successfully activated user'
      userGroup: '1'
      userHasPassword: 'User not password-less'
      userNotActivated: 'Please activate your account'
      userNotFound: 'We couldn''t find any matching users'
      volumeNotFound: 'We couldn''t find any matching volumes'
system:
  edition: pro
  live: true
  name: 'Kortrijk 2030'
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
