columnSuffix: odecfczu
contentColumnType: integer(10)
fieldGroup: a6720840-f082-4e30-bafe-b8176bf62ccc # Common
handle: pageNumber
instructions: null
name: 'page number'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
