columnSuffix: null
contentColumnType: string
fieldGroup: a6720840-f082-4e30-bafe-b8176bf62ccc # Common
handle: pollOptions
instructions: null
name: 'poll options'
searchable: false
settings:
  contentTable: '{{%matrixcontent_polloptions}}'
  maxBlocks: 2
  minBlocks: 2
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
