columnSuffix: fvkgldwp
contentColumnType: text
fieldGroup: a6720840-f082-4e30-bafe-b8176bf62ccc # Common
handle: sectionGroup
instructions: null
name: 'section group'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
