defaultPlacement: end
enableVersioning: true
handle: magazines
name: Magazines
propagationMethod: all
siteSettings:
  1c207f6e-8c50-4860-a960-ccdd0a6a4d5f: # Kortrijk 2030
    enabledByDefault: true
    hasUrls: true
    template: magazines/_entry
    uriFormat: 'magazines/{slug}'
type: channel
