defaultPlacement: end
fieldLayouts:
  0a61e53f-7f10-48b8-bda1-ab152b9d7d27:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: c37735ea-dd90-4508-aeab-f11d93861f50
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5001e355-1c2e-4928-af3b-42af9458c17e # text
            instructions: null
            label: prompt
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ae4898b-d3e5-46a9-9678-31575b973daf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 99c508e5-a234-4f38-80f1-9bade78787f0 # time
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 613f1452-7540-4a71-9087-fb41496574f3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 93d3d13d-83fd-4ffc-9ec8-99e36ab263aa # section group
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddd4266b-957d-471a-ab60-742f9f86bc50
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c3b15814-44c1-4484-beed-3b9a3e7b1ef5
        userCondition: null
handle: sections
name: sections
siteSettings:
  1c207f6e-8c50-4860-a960-ccdd0a6a4d5f: # Kortrijk 2030
    hasUrls: true
    template: null
    uriFormat: 'sections/{slug}'
structure:
  maxLevels: null
  uid: 77a3f2ae-29f2-47c1-97a6-a0a049b7afc9
